# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jiKGX4EgtlGD85dKxHPTDsigkmNR5aE
"""

import pandas as pd
import requests
import io
import streamlit as st


# --- Page configuration ---
st.set_page_config(
    page_title="Participants' Data",
    page_icon="",
    layout="wide"
)


# --- Load data ---
API_TOKEN = "d87b11826e9b2b08b3fcdc72e63c6830d29579da"

CSV_URL = (
    "https://eu.kobotoolbox.org/api/v2/assets/"
    "aEFQaUj3cV7jjRzKoet8ax/export-settings/"
    "esBqoUaYY8XrKVT2cGbChgc/data.csv"
)


@st.cache_data
def load_data():
    response = requests.get(
        CSV_URL,
        headers={"Authorization": f"Token {API_TOKEN}"}
    )

    response.raise_for_status()

    loaded_df = pd.read_csv(
        io.StringIO(response.text),
        sep=";"
    )

    return loaded_df


try:
    df = load_data()
    st.success(f" Loaded {len(df)} records")

except requests.exceptions.RequestException as error:
    st.error(f"Unable to load data from KoboToolbox: {error}")
    st.stop()

except Exception as error:
    st.error(f"An error occurred while processing the data: {error}")
    st.stop()


# --- Configure your specific columns here ---
NAME_COLUMN = "Name"
DATE_COLUMN = "Activity Date"


# --- Validate required columns ---
missing_columns = [
    column
    for column in [NAME_COLUMN, DATE_COLUMN]
    if column not in df.columns
]

if missing_columns:
    st.error(
        "The following required columns were not found in the dataset: "
        + ", ".join(missing_columns)
    )
    st.stop()


# --- Pre-process the date column to extract months ---
df["_month"] = pd.to_datetime(
    df[DATE_COLUMN],
    errors="coerce"
).dt.strftime("%B %Y")


# Build a sorted list of unique months
month_options = ["All"] + sorted(
    df["_month"].dropna().unique().tolist(),
    key=lambda x: pd.to_datetime(x, format="%B %Y")
)


# Build a sorted list of unique names
name_options = ["All"] + sorted(
    df[NAME_COLUMN]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)


# --- Application title ---
st.title("Participants' Data")

st.write(
    "Use the filters below to search records by name and activity month."
)


# --- Filters ---
filter_column_1, filter_column_2, filter_column_3 = st.columns(3)


with filter_column_1:
    name_contains = st.text_input(
        "Name contains:",
        value=""
    )


with filter_column_2:
    name_pick = st.selectbox(
        "Or pick name:",
        options=name_options
    )


with filter_column_3:
    month = st.selectbox(
        "Month:",
        options=month_options
    )


# --- Filter function ---
filtered = df.copy()


# --- Filter by Name ---
if name_contains:
    filtered = filtered[
        filtered[NAME_COLUMN]
        .astype(str)
        .str.contains(
            name_contains,
            case=False,
            na=False
        )
    ]

elif name_pick != "All":
    filtered = filtered[
        filtered[NAME_COLUMN]
        .astype(str)
        .eq(name_pick)
    ]


# --- Filter by Month ---
if month != "All":
    filtered = filtered[
        filtered["_month"] == month
    ]


# Drop helper column before display/export
display_df = filtered.drop(
    columns=["_month"],
    errors="ignore"
)


# --- Display record count ---
st.write(
    f"### Showing {len(display_df)} matching records"
)


# --- Display first 100 matching records ---
st.dataframe(
    display_df.head(100),
    use_container_width=True,
    hide_index=True
)


# --- Save filtered data to Excel for download ---
excel_buffer = io.BytesIO()

with pd.ExcelWriter(
    excel_buffer,
    engine="openpyxl"
) as writer:
    display_df.to_excel(
        writer,
        index=False,
        sheet_name="Filtered Data"
    )

excel_data = excel_buffer.getvalue()


# --- Download button ---
st.download_button(
    label="Download Excel",
    data=excel_data,
    file_name="Download.xlsx",
    mime=(
        "application/vnd.openxmlformats-officedocument."
        "spreadsheetml.sheet"
    )
)